export const ROUTES = {
	DASHBOARD: "/dashboard",
	SIGNIN: "/login",
	SIGNUP: "/registrar",
	CONFIRMATION_ACCOUNT: "/confirmacao",
	ATHLETES: "/atletas",
	NEW_ATHLETE: "/novo-atleta",
	SETTINGS: "/configuracoes",
	EXERCISES: "/exercicios",
	NEW_EXERCISE: "/exercicios/novo",
	ATHLETE_MORE_INFO: "/atleta/:athleteId",
	NEW_TRAINING: "/atleta/:athleteId/novo-treino",
	UPDATE_WORKOUT: "/atleta/:athleteId/editar/:workoutId",
	VERIFICATION: "/verificacao",
	UPDATE_ATHLETE: "/atleta/:athleteId/editar-atleta",
} as const;
