import type { Exercise } from "@core/domain/exercise";

export const seedExercises: Omit<Exercise, "id">[] = [
	{
		equipment: "Barra",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteos",
		target: "S",
		name: "LB Squat",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Gluteos",
		secondaryMuscle: "Quadriceps",
		target: "D",
		name: "Deadlift Convencional",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Posteriores",
		secondaryMuscle: "Gluteos",
		target: "D",
		name: "Stiff Leg Deadlift",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteos",
		target: "S",
		name: "Afundo",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		target: null,
		name: "Cadeira Extensora",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		target: "B",
		name: "Supino Reto",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		target: "B",
		name: "Spotto Press",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Adutor",
		secondaryMuscle: null,
		target: null,
		name: "Cadeira Adutora",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Deltoides",
		secondaryMuscle: null,
		target: null,
		name: "Desenvolvimento com Halteres",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Deltoides",
		secondaryMuscle: null,
		target: null,
		name: "Elevação Lateral",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Triceps",
		secondaryMuscle: null,
		target: null,
		name: "Triceps Testa",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Biceps",
		secondaryMuscle: null,
		target: null,
		name: "Rosca Martelo",
	},
];
