import type { Exercise } from "@core/domain/exercise";

export const seedExercises: Omit<Exercise, "id">[] = [
	{
		equipment: "Barra",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteos",
		target: "S",
		name: "LB Squat",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Gluteos",
		secondaryMuscle: "Quadriceps",
		target: "D",
		name: "Deadlift Convencional",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Posteriores",
		secondaryMuscle: "Gluteos",
		target: "D",
		name: "Stiff Leg Deadlift",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteos",
		target: "S",
		name: "Afundo",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		target: null,
		name: "Cadeira Extensora",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		target: "B",
		name: "Supino Reto",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		target: "B",
		name: "Spotto Press",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Adutor",
		secondaryMuscle: null,
		target: null,
		name: "Cadeira Adutora",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Deltoides",
		secondaryMuscle: null,
		target: null,
		name: "Desenvolvimento com Halteres",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Deltoides",
		secondaryMuscle: null,
		target: null,
		name: "Elevação Lateral",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Triceps",
		secondaryMuscle: null,
		target: null,
		name: "Triceps Testa",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Biceps",
		secondaryMuscle: null,
		target: null,
		name: "Rosca Martelo",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Dorsal",
		secondaryMuscle: null,
		target: null,
		name: "Pendlay Row",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Dorsal",
		secondaryMuscle: null,
		target: null,
		name: "Puxada Frente",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Dorsal",
		secondaryMuscle: null,
		target: null,
		name: "Remada Maquina ou polia",
	},
	{
		equipment: "Halter",
		primaryMuscle: "Biceps",
		secondaryMuscle: null,
		target: null,
		name: "Rosca Biceps",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		target: "S",
		name: "Front Squat",
	},
	{
		equipment: "Barra",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		target: "B",
		name: "Paused Vench 3'",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		target: null,
		name: "Leg Press",
	},
	{
		equipment: "Maquina",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		target: null,
		name: "Hack Machine",
	},
	{
		name: "Supino com halteres",
		target: "B",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		equipment: "Barra",
	},
	{
		name: "Agachamento 301",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		equipment: "Barra",
	},
	{
		name: "Pull down",
		primaryMuscle: "Dorsal",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "Facepull",
		primaryMuscle: "Dorsal",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "Goblet Squat",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: null,
		target: null,
		equipment: "Halter",
	},
	{
		name: "Agachamento com pausa 2'",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
		equipment: "Barra",
	},
	{
		name: "Deadlift com pausa",
		target: "D",
		primaryMuscle: "Gluteo",
		secondaryMuscle: "Posteriores",
		equipment: "Barra",
	},
	{
		name: "Bulgaro com barra",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
		equipment: "Barra",
	},
	{
		name: "Bulgaro com halteres",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
		target: null,
		equipment: "Halter",
	},
	{
		name: "Larsen Press",
		target: "B",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		equipment: "Barra",
	},
	{
		name: "Sumô DL",
		target: "D",
		primaryMuscle: "Gluteo",
		secondaryMuscle: "Posteriores",
		equipment: "Barra",
	},
	{
		name: "RDL Unilateral",
		primaryMuscle: "Posteriores",
		secondaryMuscle: "Gluteo",
		target: null,
		equipment: "Halter",
	},
	{
		name: "HB Squat",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
		equipment: "Barra",
	},
	{
		name: "Paused Bench 2'",
		target: "B",
		primaryMuscle: "Peitoral",
		secondaryMuscle: "Triceps",
		equipment: "Barra",
	},
	{
		name: "Military Press",
		primaryMuscle: "Deltoides",
		target: null,
		secondaryMuscle: null,
		equipment: "Halter",
	},
	{
		name: "Triceps Polia",
		primaryMuscle: "Triceps",
		equipment: "Maquina",
		target: null,
		secondaryMuscle: null,
	},
	{
		name: "Cadeira Flexora",
		primaryMuscle: "Posteriores",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "Mesa Flexora",
		primaryMuscle: "Posteriores",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "Flexora (Cadeira ou Mesa)",
		primaryMuscle: "Posteriores",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "Seals Row",
		primaryMuscle: "Dorsal",
		secondaryMuscle: "Biceps",
		equipment: "Halter",
		target: null,
	},
	{
		name: "Elevação Pélvica",
		primaryMuscle: "Gluteo",
		secondaryMuscle: null,
		equipment: "Barra",
		target: null,
	},
	{
		name: "ABS Roller",
		primaryMuscle: "Abdomen",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "ABS Rollout na bola",
		primaryMuscle: "Abdomen",
		secondaryMuscle: null,
		equipment: "Maquina",
		target: null,
	},
	{
		name: "Box Squat LB",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
		equipment: "Barra",
	},
	{
		name: "Box Squat HB",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
		equipment: "Barra",
	},
	{
		name: "Triceps Coice",
		primaryMuscle: "Triceps",
		secondaryMuscle: null,
		equipment: "Halter",
		target: null,
	},
	{
		name: "Paused Box Squat LB",
		equipment: "Barra",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
	},
	{
		name: "Paused Box Squat HB",
		equipment: "Barra",
		target: "S",
		primaryMuscle: "Quadriceps",
		secondaryMuscle: "Gluteo",
	},
];
