service: Grypp
useDotenv: true
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-openapi-documenter
  
package:
  individually: true
  excludeDevDependencies: true
  
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentMethod: direct
  architecture: arm64
  accessKeyId: ${env:AWS_ACCESS_KEY_ID}
  secretAccessKeyId: ${env:AWS_SECRET_ACCESS_KEY}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cognito-idp:AdminGetUser"
          Resource: !GetAtt GryppUserPool.Arn
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: 
            - !GetAtt GryppTable.Arn
            - !Sub ${GryppTable.Arn}/index/EmailIndex
            - !Sub ${GryppTable.Arn}/index/GSI1Index
  environment:
    COGNITO_POOL_ID: !Ref GryppUserPool
    COGNITO_POOL_CLIENT_ID: !Ref GryppUserPoolClient
    STAGE: ${self:provider.stage}
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt GryppUserPool.ProviderURL
        audience:
          - !Ref GryppUserPoolClient
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - '*'
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
          
resources:
  Resources:
    GryppUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: GryppUserPool-${self:provider.stage}
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - Name: given_name
            Required: true
            Mutable: true
            AttributeDataType: String
          - Name: family_name
            Required: true
            Mutable: true
            AttributeDataType: String
    GryppUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties: 
        ClientName: GryppUserPoolClient-${self:provider.stage}
        UserPoolId: !Ref GryppUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 4
        RefreshTokenValidity: 56
    GryppTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: GryppTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: GSI1Index
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        
custom:
  documentation: ${file(serverless.doc.yml):documentation}
  stages:
    - dev
    - prod
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - '@aws-sdk/*'
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10 
    
functions:
  cognitoCustomMessage:
    handler: src/server/functions/auth/cognitoCustomMessage.handler
    events:
      - cognitoUserPool:
          pool: GryppUserPool-${self:provider.stage}
          trigger: CustomMessage
          existing: true
          forceDeploy: true
  profile:
    handler: src/server/functions/auth/profile.handler
    events:
      - httpApi:
          method: GET
          path: /auth/profile
          authorizer:
            name: CognitoAuthorizer
          documentation: ${file(src/server/functions/auth/profile/handler.doc.yml):profile}
  accountConfirmation:
    handler: src/server/functions/auth/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/account-confirmation
          documentation: ${file(src/server/functions/auth/accountConfirmation/handler.doc.yml):accountConfirmation}
  signin:
    handler: src/server/functions/auth/signin.handler
    events:
      - httpApi:
          method: POST
          path: /auth/signin
          documentation: ${file(src/server/functions/auth/signin/handler.doc.yml):signin}
  createAthlete:
    handler: src/server/functions/athlete/create.handler
    events:
      - httpApi:
          method: POST
          path: /athlete
          documentation: ${file(src/server/functions/athlete/create/handler.doc.yml):createAthlete}
          authorizer:
            name: CognitoAuthorizer
  getAllByCoachId:
    handler: src/server/functions/athlete/getAllByCoachId.handler
    events:
      - httpApi:
          method: GET
          path: /athlete/{coachId}
          documentation: ${file(src/server/functions/athlete/getAllByCoachId/handler.doc.yml):getAllByCoachId}
          authorizer:
            name: CognitoAuthorizer
  createExercise:
    handler: src/server/functions/exercise/create.handler
    events:
      - httpApi:
          method: POST
          path: /exercise
          authorizer:
            name: CognitoAuthorizer
  getAllExercises:
    handler: src/server/functions/exercise/getAll.handler
    events:
      - httpApi:
          method: GET
          path: /exercise
          documentation: ${file(src/server/functions/exercise/getAll/handler.doc.yml):getAll}
          authorizer:
            name: CognitoAuthorizer
  createWorkout:
    handler: src/server/functions/workout/create.handler
    events:
      - httpApi:
          method: POST
          path: /workout
          documentation: ${file(src/server/functions/workout/create/handler.doc.yml):create}
          authorizer:
            name: CognitoAuthorizer
  getAllWorkoutByAthleteId:
    handler: src/server/functions/workout/getAllByAthleteId.handler
    events:
      - httpApi:
          method: GET
          path: /workout/{athleteId}
          documentation: ${file(src/server/functions/workout/getAllByAthleteId/handler.doc.yml):getAllByAthleteId}
          authorizer:
            name: CognitoAuthorizer
  deleteWorkout:
    handler: src/server/functions/workout/delete.handler
    events:
      - httpApi:
          method: DELETE
          path: /workout
          documentation: ${file(src/server/functions/workout/delete/handler.doc.yml):delete}
          authorizer:
            name: CognitoAuthorizer
  updateWorkout:
    handler: src/server/functions/workout/update.handler
    events:
      - httpApi:
          method: PUT
          path: /workout
          authorizer:
            name: CognitoAuthorizer
  updateSettings:
    handler: src/server/functions/settings/update.handler
    events:
      - httpApi:
          method: PUT
          path: /settings
          documentation: ${file(src/server/functions/settings/update/handler.doc.yml):update}
          authorizer:
            name: CognitoAuthorizer
  getSettingsByUser:
    handler: src/server/functions/settings/getByUser.handler
    events:
      - httpApi:
          method: GET
          path: /settings
          documentation: ${file(src/server/functions/settings/getByUser/handler.doc.yml):getByUser}
          authorizer:
            name: CognitoAuthorizer
  createCoach:
    handler: src/server/functions/coach/create.handler
    events:
      - httpApi:
          method: POST
          path: /coach
          documentation: ${file(src/server/functions/coach/create/handler.doc.yml):createCoach}
          